### ISSUE TITLE
#TODO

### ISSUE THREAD

**Issue by Liki4** [vidar-team/EvilMySQL#1]
- [ ]  SSL 流量处理，和客户端协商，先解密再处理
- [ ]  不同客户端的交互，例如 Datagrip，Navicat 等
- [ ]  Drop 掉 0x00 0x00 0x00 0x03 应该是不合理的，抓包研究一下看看为什么，应该怎么改
- [ ]  能否一次性插入多个包，读取多个文件
- [ ]  JDBC MySQL Client Attack
- [ ]  抛弃流量转发实现完整 MySQL

- [ ]  更多功能...
